if  ENV['THE_CITY_APP_SECRET'].present?
  THE_CITY_APP_SECRET = ENV['THE_CITY_APP_SECRET']
  THE_CITY_AUTH_URL = ENV['THE_CITY_AUTH_URL']
else
  THECITY_CONFIG = YAML.load_file("#{::Rails.root}/config/thecity.yml")[::Rails.env]
  THE_CITY_APP_SECRET = THECITY_CONFIG['THE_CITY_APP_SECRET']
  THE_CITY_AUTH_URL = THECITY_CONFIG['THE_CITY_AUTH_URL']
end